const constants = {
	MISC_TEXT: {
		LOG_IN: 'Iniciar sesión',
		EMAIL_PLACEHOLDER: 'juan@gmail.com',
		PASSWORD_PLACEHOLDER: 'Escribe tu contraseña',
		EMAIL_LABEL: 'Correo electrónico',
		PASSWORD_LABEL: 'Contraseña',
		LOGIN_BUTTON_TEXT: 'Iniciar sesión',
		START_PAGE_DRAWER_ITEM: 'Inicio',
		TRANSFER_PAGE_DRAWER_ITEM: 'Transferir',
		RECHARGE_PAGE_DRAWER_ITEM: 'Recargar',
		EXCHANGE_PAGE_DRAWER_ITEM: 'Intercambiar',
		PROFILE_PAGE_DRAWER_ITEM: 'Perfil',
		HELP_PAGE_DRAWER_ITEM: 'Ayuda',
		LOGOUT_DRAWER_ITEM: 'Cerrar sesión',
		START_PAGE_GREETING: '¡Hola',
		START_PAGE_SUBTITLE: 'Mis saldos',
		CHILEAN_PESO: 'Peso Chileno',
		USD_TETHER: 'Tether',
		BITCOIN: 'Bitcoin',
		YOU_RECEIVED: 'Recibiste', // sent
		YOU_SENT: 'Transferiste', // transfer
		YOU_RECHARGED: 'Recargaste', // deposit
		YOU_EXCHANGED: 'Intercambiaste', // exchange
		UNKNOWN_TRANSACTION: 'Transacción desconocida',
		TETHER_SHORT: 'USDT',
		BITCOIN_SHORT: 'BTC',
		CLP_SHORT: 'CLP',
		HISTORY: 'Historial',
		CONTINUE: 'Continuar',
		BACK: 'Atrás',
		TRANSACTION_PAGE_TITLE: '¿Qué deseas intercambiar?',
		BALANCE_AVAILABLE: 'Saldo disponible',
		EXCHANGE: 'Intercambiar',
		AMOUNT_TO_EXCHANGE: 'Monto a intercambiar',
		I_WANT_TO_RECEIVE: 'Quiero recibir',
		TRANSACTION_SUMMARY: 'Resumen de la transacción',
		TOTAL_TO_RECEIVE: 'Total a recibir',
		EXCHANGE_RATE: 'Tasa de cambio',
		SUCCESFULL_TRANSACTION: '¡Intercambio exitoso!',
		SUCCESS_MODAL_TEXT: 'Ya cuentas con los %currency% en tu cuenta',
	},
	PAGES: {
		LOGIN: '/',
		START: '/start',
		TRANSFER: '/transfer',
		RECHARGE: '/recharge',
		EXCHANGE: '/exchange',
		PROFILE: '/profile',
		HELP: '/help',
		WIP_PAGE: '/wip',
	},
};

export default constants;
